#!/bin/bash

DIR=$(dirname $0)

mkdir -p $DIR/$1
cp -a $DIR/template/. $DIR/$1/

OLD=solution
NEW=$(echo $1 | cut -d / -f 2)

sed -i "s,$OLD,$NEW,g" $DIR/$1/Makefile
mv $DIR/$1/$OLD.cpp $DIR/$1/$NEW.cpp
mv $DIR/$1/$OLD.py $DIR/$1/$NEW.py
